import { useEffect, useMemo, useState } from 'react';
import { House, LayoutGrid, Zap, Sparkles, Power, ArrowLeft, ArrowUpRight, Search, Car, Sun, Battery, Plug, Thermometer, Lightbulb, Activity, RotateCcw, Moon, ChevronRight } from 'lucide-react';
import type { HAEntity, HAStateMap } from '@/lib/ha-client';
import { mapHAStatesToRooms, mapHAStatesToScenes, mapHAStatesToAutomations, HA_ENTITIES, INDOOR_AIR_SENSORS } from '@/lib/ha-types';
import { compareRooms } from '@/lib/room-order';
import './preview.css';

const unavailable = (e?: HAEntity) => !e || ['unavailable', 'unknown'].includes(e.state);
const name = (e?: HAEntity) => String(e?.attributes.friendly_name || e?.entity_id || 'Device');
const display = (e?: HAEntity, unit = '') => { if (unavailable(e)) return 'Unavailable'; const n = Number(e!.state); return `${e!.state.trim() !== '' && Number.isFinite(n) ? n.toLocaleString([], { maximumFractionDigits: unit === '%' ? 0 : 1 }) : e!.state.replaceAll('_', ' ')}${unit}`; };
const when = (value: unknown) => value && Number.isFinite(Date.parse(String(value))) ? new Date(String(value)).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }) : 'No recorded run';
type Change = { id: string; state?: string; attributes?: Record<string, unknown> };
type Event = { title: string; time: string; before: HAStateMap };
type Plan = { name: string; changes: Change[]; notes?: string };

// Intentionally isolated from App and HAClient. The only network operation is
// GET /api/states. Every control writes to an in-memory copy, never HA.
export default function HomePreview() {
  const [source, setSource] = useState<HAStateMap | null>(null);
  const [states, setStates] = useState<HAStateMap>({});
  const [error, setError] = useState('');
  const [captured, setCaptured] = useState('');
  const [page, setPage] = useState('now');
  const [roomId, setRoomId] = useState<string | null>(null);
  const [detail, setDetail] = useState<string | null>(null);
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const [events, setEvents] = useState<Event[]>([]);
  const [notice, setNotice] = useState('');
  const [plan, setPlan] = useState<Plan | null>(null);
  const [theme, setTheme] = useState('light');
  useEffect(() => { const controller = new AbortController(); fetch('/api/states', { signal: controller.signal }).then(r => { if (!r.ok) throw Error(`Unable to load Home Assistant (${r.status})`); return r.json(); }).then((data: HAEntity[]) => { const map = Object.fromEntries(data.map(e => [e.entity_id, e])); setSource(map); setStates(map); setCaptured(new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })); }).catch(e => { if (e.name !== 'AbortError') setError(e.message); }); return () => controller.abort(); }, []);
  useEffect(() => { window.scrollTo(0, 0); }, [page, roomId, detail, plan]);
  const rooms = useMemo(() => mapHAStatesToRooms(states).sort(compareRooms), [states]);
  const scenes = useMemo(() => mapHAStatesToScenes(states), [states]);
  const automations = useMemo(() => mapHAStatesToAutomations(states), [states]);
  const lights = Object.values(states).filter(e => e.entity_id.startsWith('light.'));
  const room = rooms.find(r => r.id === roomId);
  const entity = detail ? states[detail] : undefined;
  const controls = Object.values(states).filter(e => /^(light|switch|climate|cover|lock|select|number|button|media_player|sensor|binary_sensor)\./.test(e.entity_id));
  const navigate = (next: string) => { setPage(next); setRoomId(null); setDetail(null); setPlan(null); setQuery(''); setFilter('all'); };
  const apply = (title: string, changes: Change[]) => {
    setEvents(old => [{ title, time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), before: states }, ...old]);
    setStates(old => { const next = { ...old }; changes.forEach(c => { if (old[c.id] && !unavailable(old[c.id])) next[c.id] = { ...old[c.id], state: c.state ?? old[c.id].state, attributes: { ...old[c.id].attributes, ...c.attributes } }; }); return next; });
    setNotice(`${title} · simulated`);
  };
  const change = (e: HAEntity, state: string) => apply(`${name(e)}: ${state}`, [{ id: e.entity_id, state }]);
  const attr = (e: HAEntity, key: string, value: unknown) => apply(`${name(e)} adjusted`, [{ id: e.entity_id, attributes: { [key]: value } }]);
  const undo = () => { const last = events[0]; if (!last) return; setStates(last.before); setEvents(old => old.slice(1)); setNotice('Previous preview settings restored'); };
  const open = (id: string) => { setDetail(id); setPlan(null); };
  const heading = (eyebrow: string, title: string, subtitle?: string) => <header className="np-heading"><span>{eyebrow}</span><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</header>;
  const back = (fn: () => void, text: string) => <button className="np-back" onClick={fn}><ArrowLeft size={18} />{text}</button>;
  const reading = (id: string, unit = '') => display(states[id], unit);
  const toggle = (e: HAEntity) => <button className="np-power" aria-label={`Toggle ${name(e)}`} aria-pressed={e.state === 'on'} disabled={unavailable(e)} onClick={() => change(e, e.state === 'on' ? 'off' : 'on')}><Power size={19} /></button>;
  const deviceRow = (e: HAEntity) => <div className="np-device" key={e.entity_id}><button className="np-device-open" onClick={() => open(e.entity_id)}><span className="np-device-symbol">{e.entity_id.startsWith('light.') ? <Lightbulb size={21} /> : e.entity_id.startsWith('climate.') ? <Thermometer size={21} /> : <Plug size={21} />}</span><span><strong>{name(e)}</strong><small>{unavailable(e) ? 'Unavailable' : e.entity_id.startsWith('button.') ? `Last used: ${when(e.state)}` : display(e, String(e.attributes.unit_of_measurement || ''))}{e.state === 'on' && e.attributes.brightness != null ? ` · ${Math.round(Number(e.attributes.brightness) / 255 * 100)}%` : ''}</small></span></button>{/^(light|switch)\./.test(e.entity_id) ? toggle(e) : <button className="np-icon" aria-label={`Open ${name(e)}`} onClick={() => open(e.entity_id)}><ChevronRight size={20} /></button>}</div>;
  const sensorBlock = (id: string) => { const cfg = INDOOR_AIR_SENSORS[id]; return cfg ? <div className="np-readings">{Object.entries(cfg).map(([kind, eid]) => <div key={eid}><small>{{ temp: 'Temperature', humidity: 'Humidity', co2: 'CO₂', pm25: 'PM2.5' }[kind]}</small><strong>{reading(eid, { temp: '°C', humidity: '%', co2: ' ppm', pm25: ' µg/m³' }[kind])}</strong></div>)}</div> : null; };
  const makeScene = (id: string) => { const e = states[id]; const ids = Array.isArray(e.attributes.entity_id) ? e.attributes.entity_id as string[] : []; setPlan({ name: name(e), changes: [], notes: ids.length ? `Affects ${ids.map(id => name(states[id]) || id).join(", ")}. Target settings are not included in this snapshot; a real activation would run the existing scene.` : 'Home Assistant does not expose the scene’s target settings in this snapshot. A real activation would run the existing scene.' }); };
  let content;
  if (!source) content = <>{heading('DESIGN PREVIEW', 'Your home, loading.', error || 'Reading a snapshot from Home Assistant…')}{error && <button className="np-primary" onClick={() => window.location.reload()}>Try again</button>}</>;
  else if (plan) content = <>{back(() => setPlan(null), 'Back')}{heading('REVIEW ACTION', plan.name, 'Try this action in the preview.')}<div className="np-panel">{plan.changes.map(c => <div className="np-line" key={c.id}><strong>{name(states[c.id])}</strong><span>{c.state || Object.entries(c.attributes || {}).map(([k,v]) => `${k.replaceAll('_',' ')}: ${v}`).join(', ')}</span></div>)}{plan.notes && <p>{plan.notes}</p>}</div><button className="np-primary" onClick={() => { apply(plan.name, plan.changes); setPlan(null); }}>Simulate {plan.name.toLowerCase()}</button><p className="np-caption">{plan.changes.length ? 'All changes can be undone in Activity.' : 'Records a preview action only; device settings are not guessed.'}</p></>;
  else if (entity) {
    const domain = entity.entity_id.split('.')[0];
    const modes = entity.attributes.supported_color_modes as string[] || [];
    content = <>{back(() => setDetail(null), 'Back')}{heading(domain.toUpperCase(), name(entity), unavailable(entity) ? 'Unavailable in the Home Assistant snapshot' : `Snapshot state: ${entity.state.replaceAll('_',' ')}`)}
    <div className="np-panel np-detail">
    {['light','switch','automation'].includes(domain) && <div className="np-line"><strong>Power</strong>{toggle(entity)}</div>}
    {domain === 'light' && <>
      {!modes.every(m => m === 'onoff') && <label className="np-range">Brightness <output>{Math.round(Number(entity.attributes.brightness || 0) / 255 * 100)}%</output><input aria-label="Brightness" type="range" min="0" max="255" value={Number(entity.attributes.brightness || 0)} disabled={unavailable(entity)} onChange={e => { const brightness = Number(e.target.value); apply(`${name(entity)} brightness`, [{ id: entity.entity_id, state: brightness ? 'on' : 'off', attributes: { brightness } }]); }} /></label>}
      {modes.includes('color_temp') && <label className="np-range">White temperature <output>{String(entity.attributes.color_temp_kelvin || '—')} K</output><input aria-label="White temperature" type="range" min={Number(entity.attributes.min_color_temp_kelvin || 2000)} max={Number(entity.attributes.max_color_temp_kelvin || 6500)} value={Number(entity.attributes.color_temp_kelvin || 2700)} disabled={unavailable(entity)} onChange={e => attr(entity, 'color_temp_kelvin', Number(e.target.value))} /></label>}
      {modes.some(m => ['hs','xy','rgb','rgbw','rgbww'].includes(m)) && <label className="np-field">Light colour<input type="color" aria-label="Light colour" disabled={unavailable(entity)} value={String(entity.attributes.preview_color || (Array.isArray(entity.attributes.rgb_color) ? '#' + (entity.attributes.rgb_color as number[]).slice(0,3).map(v=>Math.round(v).toString(16).padStart(2,'0')).join('') : '#ffffff'))} onChange={e => attr(entity,'preview_color',e.target.value)} /></label>}
    </>}
    {domain === 'climate' && <><label className="np-field">Mode<select value={entity.state} disabled={unavailable(entity)} onChange={e => change(entity,e.target.value)}>{(entity.attributes.hvac_modes as string[] || []).map(m => <option key={m}>{m}</option>)}</select></label><label className="np-range">Target temperature <output>{String(entity.attributes.temperature ?? '—')}°C</output><input aria-label="Target temperature" type="range" min={Number(entity.attributes.min_temp || 16)} max={Number(entity.attributes.max_temp || 30)} step={Number(entity.attributes.target_temp_step || .5)} value={Number(entity.attributes.temperature || 21)} disabled={unavailable(entity)} onChange={e => attr(entity,'temperature',Number(e.target.value))} /></label>{['fan_modes','preset_modes'].map(key => Array.isArray(entity.attributes[key]) && <label className="np-field" key={key}>{key === 'fan_modes' ? 'Fan' : 'Preset'}<select disabled={unavailable(entity)} value={String(entity.attributes[key === 'fan_modes' ? 'fan_mode' : 'preset_mode'] || '')} onChange={e => attr(entity,key === 'fan_modes' ? 'fan_mode' : 'preset_mode',e.target.value)}><option value="">Not set</option>{(entity.attributes[key] as string[]).map(m => <option key={m}>{m}</option>)}</select></label>)}</>}
    {domain === 'select' && <label className="np-field">Setting<select value={entity.state} disabled={unavailable(entity)} onChange={e => change(entity,e.target.value)}>{(entity.attributes.options as string[] || []).map(m => <option key={m}>{m}</option>)}</select></label>}
    {domain === 'number' && <label className="np-range">Value <output>{entity.state} {String(entity.attributes.unit_of_measurement || '')}</output><input aria-label={name(entity)} type="range" min={Number(entity.attributes.min || 0)} max={Number(entity.attributes.max || 100)} step={Number(entity.attributes.step || 1)} value={Number(entity.state) || 0} disabled={unavailable(entity)} onChange={e => change(entity,e.target.value)} /></label>}
    {domain === 'lock' && <button className="np-primary" disabled={unavailable(entity)} onClick={() => change(entity,entity.state === 'locked' ? 'unlocked' : 'locked')}>{entity.state === 'locked' ? 'Unlock' : 'Lock'} · preview</button>}
    {domain === 'cover' && <div className="np-actions"><button disabled={unavailable(entity) || !(Number(entity.attributes.supported_features) & 1)} onClick={() => change(entity,'open')}>Open</button><button disabled={unavailable(entity) || !(Number(entity.attributes.supported_features) & 2)} onClick={() => change(entity,'closed')}>Close</button></div>}
    {domain === 'button' && <button className="np-primary" disabled={unavailable(entity)} onClick={() => apply(`${name(entity)} pressed`,[])}>Try action</button>}
    {['sensor','binary_sensor'].includes(domain) && <div className="np-line"><strong>Reading</strong><span>{display(entity, String(entity.attributes.unit_of_measurement || ''))}</span></div>}
    {domain === 'media_player' && <p>Media playback is not implemented in this concept yet. This device remains discoverable here.</p>}
    </div><p className="np-caption">Preview only. No command is sent to this device.</p><details className="np-technical"><summary>Device information</summary><p>{entity.entity_id}</p><p>Last updated: {when(entity.last_updated)}</p></details></>;
  } else if (room) content = <>{back(() => setRoomId(null), 'Rooms')}{heading('YOUR SPACE', room.name)}{sensorBlock(room.id)}<div className="np-section"><h2>Lighting</h2>{room.lights.length > 0 && <button onClick={() => setPlan({ name: `Turn off ${room.name} lights`, changes: room.lights.filter(l => !unavailable(states[l.id])).map(l => ({ id:l.id,state:'off' })) })}>All off</button>}</div><div className="np-panel">{room.lights.length ? room.lights.map(l => deviceRow(states[l.id])) : <p>No lights assigned to this room.</p>}</div>{room.switches.length > 0 && <><h2>Power points</h2><div className="np-panel">{room.switches.map(s => deviceRow(states[s.id]))}</div></>}{room.climate.length > 0 && <><h2>Climate</h2><div className="np-panel">{room.climate.map(c => deviceRow(states[c.id]))}</div></>}<button className="np-text" onClick={() => navigate('devices')}>Find another device <ArrowUpRight size={16} /></button></>;
  else if (page === 'now') content = <>{heading('YOUR HOME, RIGHT NOW', 'Make yourself\nat home.', `${lights.filter(e => e.state === 'on').length} lights on · ${reading(HA_ENTITIES.outdoorWeather)}`)}
    <div className="np-scenes">{scenes.map((s,i) => <button key={s.id} onClick={() => makeScene(s.id)}>{i ? <Moon size={23} /> : <Sparkles size={23} />}<strong>{s.name}</strong><ArrowUpRight size={16} /></button>)}<button onClick={() => setPlan({ name:'All lights off',changes:lights.filter(e => !unavailable(e)).map(e => ({id:e.entity_id,state:'off'})),notes:'Power points keep their current settings.' })}><Power size={23}/><strong>Lights off</strong><ArrowUpRight size={16}/></button></div>
    <div className="np-section"><h2>Within reach</h2><button onClick={() => navigate('rooms')}>All rooms <ArrowUpRight size={16}/></button></div>
    <div className="np-favourites"><button className="np-room-hero" onClick={() => {setRoomId('living');setPage('rooms');}}><Lightbulb size={25}/><span>Living Room</span><strong>{rooms.find(r=>r.id==='living')?.lights.filter(l=>l.cardState==='on').length || 0}<small> lights on</small></strong><span className="np-hero-foot">Adjust lighting <ArrowUpRight size={18}/></span></button><button className="np-climate-hero" onClick={() => open(HA_ENTITIES.climateSplitSystem)}><Thermometer size={25}/><span>Split System</span><strong>{String(states[HA_ENTITIES.climateSplitSystem]?.attributes.current_temperature ?? '—')}<small>°</small></strong><span className="np-hero-foot">{reading(HA_ENTITIES.climateSplitSystem)} <ArrowUpRight size={18}/></span></button></div>
    <button className="np-ghost" onClick={() => navigate('ghost')}><Car size={30}/><span><strong>Ghost</strong><small>{reading(HA_ENTITIES.teslaBattery,'%')} battery · {reading(HA_ENTITIES.teslaLock)}</small></span><ArrowUpRight size={20}/></button>
    {lights.some(unavailable) && <button className="np-attention" onClick={() => {navigate('devices');setFilter('unavailable');}}> <span>{lights.filter(unavailable).length} light unavailable</span><ChevronRight size={18}/></button>}
    <button className="np-energy-link" onClick={() => navigate('energy')}><Battery size={19}/><span>Powerwall {reading(HA_ENTITIES.powerwallCharge,'%')}</span><ArrowUpRight size={17}/></button>
    </>;
  else if (page === 'rooms') content = <>{heading('YOUR SPACES','Every room.','Lighting, climate and readings, together.')}<div className="np-room-grid">{rooms.map(r => <button key={r.id} onClick={() => setRoomId(r.id)}><House size={23}/><strong>{r.name}</strong><small>{r.lights.length ? `${r.lights.filter(l=>l.cardState==='on').length} of ${r.lights.length} lights on` : 'Sensors'}{r.lights.some(l=>l.cardState==='error') ? ' · unavailable' : ''}</small><span>{INDOOR_AIR_SENSORS[r.id] ? reading(INDOOR_AIR_SENSORS[r.id].temp,'°') : 'Open room'}<ArrowUpRight size={16}/></span></button>)}</div><button className="np-primary" onClick={() => navigate('devices')}><Search size={18}/> Find any device</button></>;
  else if (page === 'devices') {
    const list = controls.filter(e => (!query || `${name(e)} ${e.entity_id}`.toLowerCase().includes(query.toLowerCase())) && (filter==='all' || filter==='unavailable' ? filter!=='unavailable' || unavailable(e) : e.entity_id.startsWith(filter+'.')));
    content = <>{back(() => navigate('rooms'),'Rooms')}{heading('DEVICE LIBRARY','Everything, found.',`${controls.length} controls and readings from Home Assistant`)}<label className="np-search"><Search size={19}/><input aria-label="Find a device" placeholder="Name, room or device…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="np-field">Show<select value={filter} onChange={e=>setFilter(e.target.value)}>{['all','light','switch','climate','cover','lock','select','number','button','media_player','sensor','binary_sensor','unavailable'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label><p className="np-caption">Power-point room assignments are unchanged. This library also includes entities not yet mapped in Tactus.</p><div className="np-panel">{list.map(deviceRow)}{!list.length && <p>No matching devices.</p>}</div></>;
  } else if (page === 'energy') content = <>{heading('ENERGY','A little perspective.','Your solar, battery and home consumption.')}<div className="np-energy-hero"><Sun size={28}/><span>Solar now</span><strong>{reading(HA_ENTITIES.solarPower)}<small> kW</small></strong><p>{reading(HA_ENTITIES.solarEnergyToday,' kWh')} generated today</p></div><div className="np-metric-grid">{[['Powerwall',HA_ENTITIES.powerwallCharge,'%'],['Home usage',HA_ENTITIES.homeLoadPower,' kW'],['Battery flow',HA_ENTITIES.powerwallFlow,' kW'],['Grid power',HA_ENTITIES.gridPower,' kW']].map(([n,id,u])=><div key={id}><small>{n}</small><strong>{reading(id,u)}</strong></div>)}</div><p className="np-caption">Signed power values shown as reported by Home Assistant. No historical chart is invented.</p><button className="np-ghost" onClick={()=>navigate('ghost')}><Car size={28}/><span><strong>Ghost</strong><small>{reading(HA_ENTITIES.teslaBattery,'%')} · {reading(HA_ENTITIES.teslaRange,' km')}</small></span><ArrowUpRight size={20}/></button><h2>Battery settings</h2><div className="np-panel">{controls.filter(e=>e.entity_id.startsWith('switch.home_')||e.entity_id===HA_ENTITIES.powerwallReserve).map(deviceRow)}</div></>;
  else if (page === 'ghost') content = <>{back(()=>navigate('now'),'Home')}{heading('MODEL 3 · HIGHLAND','Ghost.',`${reading(HA_ENTITIES.teslaTracker)} · ${reading(HA_ENTITIES.teslaLock)}`)}<div className="np-energy-hero"><Car size={36}/><strong>{reading(HA_ENTITIES.teslaBattery)}<small>%</small></strong><p>{reading(HA_ENTITIES.teslaRange,' km')} estimated range</p></div>{[
      ['Access', [HA_ENTITIES.teslaLock, HA_ENTITIES.teslaFrunk, HA_ENTITIES.teslaTrunk, HA_ENTITIES.teslaWindows]],
      ['Comfort', [HA_ENTITIES.teslaClimate, HA_ENTITIES.teslaSeatHeaterFL, HA_ENTITIES.teslaSeatHeaterFR, HA_ENTITIES.teslaSteeringWheelHeater]],
      ['Charging', ['switch.ghost_charge','number.ghost_charge_limit','number.ghost_charge_current']],
      ['Security', [HA_ENTITIES.teslaSentry, HA_ENTITIES.teslaValet]],
    ].map(([label, ids]) => <section key={String(label)}><h2>{label}</h2><div className="np-panel">{(ids as string[]).filter(id=>states[id]).map(id=>deviceRow(states[id]))}</div></section>)}<button className="np-primary" onClick={()=>{navigate('devices');setQuery('ghost');}}>All Ghost controls & readings</button></>;
  else if (page === 'routines') content = <>{heading('LET HOME HELP','Your routines.',`${scenes.length} scenes · ${automations.length} automations`)}<h2>Scenes</h2><div className="np-scenes">{scenes.map(s=><button key={s.id} onClick={()=>makeScene(s.id)}><Sparkles size={23}/><strong>{s.name}</strong><ArrowUpRight size={16}/></button>)}</div><h2>Automations</h2><div className="np-panel">{automations.map(a=><div className="np-automation" key={a.id}><div><strong>{a.name}</strong><small>{a.state==='off'?'Disabled':a.state==='unavailable'?'Unavailable':`Last run: ${when(a.lastTriggered)}`}</small></div><div className="np-actions">{toggle(states[a.id])}<button disabled={a.state==='unavailable'} onClick={()=>setPlan({name:`Run ${a.name}`,changes:[],notes:'Runs the existing Home Assistant automation. Its actions and conditions are not included in the state snapshot.'})}>Try run</button></div></div>)}</div><p className="np-caption">Timed overrides and automatic explanations are future functionality, not working features of this preview.</p></>;
  else content = <>{heading('WHAT CHANGED','Activity.', 'Your preview actions are recorded here.')}<button className="np-primary" disabled={!events.length} onClick={undo}><RotateCcw size={18}/> Undo last change</button>{!events.length && <div className="np-panel"><p>No preview actions yet. Try a light, climate control or routine.</p></div>}{events.map((e,i)=><div className="np-event" key={i}><small>{e.time} · Simulated</small><strong>{e.title}</strong></div>)}<p className="np-caption">This is not Home Assistant history. Actual automation run times appear under Routines.</p></>;
  return <div className={`np-app np-${theme}`}><div className="np-preview-bar"><span>Design lab · real snapshot / simulated controls</span><button onClick={()=>{if(source)setStates(source);setEvents([]);setNotice('Preview reset');}}>Reset</button></div><div className="np-shell"><header className="np-top"><button onClick={()=>navigate('now')}><House size={19}/> Tactus</button><div><button aria-label="Activity" onClick={()=>navigate('activity')}><Activity size={20}/></button><button aria-label="Change theme" onClick={()=>setTheme(t=>t==='light'?'dark':'light')}><Sun size={20}/></button></div></header><main className="np-main">{content}</main><div className="np-feedback" role="status">{notice || (captured ? `Snapshot at ${captured} · controls are safe to try` : 'Loading snapshot…')}</div><nav className="np-nav" aria-label="Preview navigation">{[['now','Now',House],['rooms','Rooms',LayoutGrid],['energy','Energy',Zap],['routines','Routines',Sparkles]].map(([id,label,Icon]:any)=><button key={id} aria-current={page===id || id==='rooms'&&page==='devices' ? 'page':undefined} onClick={()=>navigate(id)}><Icon size={21}/><span>{label}</span></button>)}</nav></div></div>;
}
